# Generated by Django 6.1 on 2026-08-24 12:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('8ff18f74-5530-4fa1-9a8c-b45e0ef5e39e'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('8c1f293f-49d1-4120-8383-1d9ddd8fa7de'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=100)),
                ('premium', models.IntegerField(default=0)),
                ('cover', models.IntegerField(default=0)),
                ('state', models.CharField(choices=[('new', 'New'), ('quoted', 'Quoted'), ('bound', 'Bound'), ('active', 'Active')], default='new', max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='app.customer')),
            ],
        ),
    ]
